OpenSilver/OpenSilver

- src/CSHTML5.Runtime/System.Net/WebClient.cs
Hi,
A fix about WebClient
XMLHttpRequest refuses to use content-length
See https://stackoverflow.com/questions/7210507/ajax-post-error-refused-to-set-unsafe-header-connection
> Fix WebClient error

- src/CSHTML5.Runtime/Core/Main/INTERNAL_UriHelper.cs
This time a global URI support for pack://application:,,,/ prefix
Works in the simulator, the browser and EXE.
Adding this support is very important for project that use same source code to build XAML exe and CSHTML5 project.
This allow the dev to see images in the XAML designer for the EXE version.
> Add pack://application:,,,/ support for uri

- src/Runtime/Runtime/Runtime.OpenSilver.csproj
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/PopulatingEventArgs.cs
Implementation of PopulatingEventArgs
> Add class "PopulatingEventArgs"

- src/Runtime/Runtime/Runtime.OpenSilver.csproj
- src/Runtime/Runtime/Windows.UI.Xaml.Media.Animation/WORKINPROGRESS/SplinePointKeyFrame.cs
Add an empty class in the WORKINPROGRESS
> Add class "SplinePointKeyFrame"

- src/Runtime/Runtime/Runtime.OpenSilver.csproj
- src/Runtime/Runtime/System.Xaml/IMarkupExtension.cs
The interface [IMarkupExtension](https://docs.microsoft.com/en-us/previous-versions/windows/silverlight/dotnet-windows-silverlight/gg712747(v=vs.95))
> Add interface "IMarkupExtension"

- src/Runtime/Runtime/Runtime.OpenSilver.csproj
- src/Runtime/Runtime/Windows.UI.Xaml.Controls.Primitives/WORKINPROGRESS/DatePickerTextBox.cs
Empty class for [DatePickerTextBox](https://docs.microsoft.com/en-us/previous-versions/windows/silverlight/dotnet-windows-silverlight/cc838672(v=vs.95))
> Add class "DatePickerTextBox"

- src/Runtime/Runtime/Runtime.OpenSilver.csproj
- src/Runtime/Runtime/Windows.UI.Xaml.Controls.Primitives/WORKINPROGRESS/DataGridCellsPresenter.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls.Primitives/WORKINPROGRESS/DataGridColumnHeadersPresenter.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls.Primitives/WORKINPROGRESS/DataGridDetailsPresenter.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls.Primitives/WORKINPROGRESS/DataGridFrozenGrid.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls.Primitives/WORKINPROGRESS/DataGridRowHeader.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls.Primitives/WORKINPROGRESS/DataGridRowsPresenter.cs
* DataGridCellsPresenter
* DataGridColumnHeadersPresenter
* DataGridDetailsPresenter
* DataGridFrozenGrid
* DataGridRowHeader
* DataGridRowsPresenter
> Add DataGrid primitives

- src/Runtime/Runtime/Runtime.OpenSilver.csproj
- src/Runtime/Runtime/Windows.UI.Xaml.Controls.Primitives/WORKINPROGRESS/AccordionButton.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls.Primitives/WORKINPROGRESS/ExpandableContentControl.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/WORKINPROGRESS/ButtonSpinner.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/WORKINPROGRESS/IUpdateVisualState.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/WORKINPROGRESS/Spinner.cs
* AccrodionButton
* ExpandableContentControl
* ButtonSpinner
> Add SilverlightToolkit components

- src/Runtime/Runtime/Runtime.OpenSilver.csproj
- src/Runtime/Runtime/Windows.UI.Xaml.Controls.Primitives/WORKINPROGRESS/DataGridColumnHeader.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls.Primitives/WORKINPROGRESS/ExpandableContentControl.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/AccordionSelectionMode.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/DataGridHeadersVisibility.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/DataGridRowDetailsVisibilityMode.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/ExpandDirection.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/SelectionSequence.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/WORKINPROGRESS/Accordion.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/WORKINPROGRESS/AutoCompleteBox.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/WORKINPROGRESS/Calendar.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/WORKINPROGRESS/DataGrid.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/WORKINPROGRESS/DataGridColumn.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/WORKINPROGRESS/DatePicker.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/WORKINPROGRESS/NumericUpDown.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/WORKINPROGRESS/TimePicker.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Media.Animation/WORKINPROGRESS/SplineColorKeyFrame.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Media/WORKINPROGRESS/PlaneProjection.cs
* ExpandableContentControl
* Accordion
* AccordionItem
* DataGrid
* DataGridColumn
* DataGridColumnHeader
* NumericUpDown
* TimePicker
* AutoCompleteBox
* Calendar
* SplineColorKeyFrame
* PlaneProjection
> Add properties

- src/Runtime/Runtime/Windows.System/VirtualKey.cs
Compilation error fixed regarding a VirtualKey commit
> VirtualKey compile error fixed

- src/Runtime/Runtime/PublicAPI/Interop/INTERNAL_JSObjectReference.cs
- src/Runtime/Scripts/OpenSilver.js
1. Pass args to C#
2. Handle args in the C# code
> Pass args from js code to C# code

- src/Runtime/Runtime/Windows.UI.Xaml.Controls/DatePicker.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/INTERNAL_DateTimePickerBase.cs
Update SelectedDate when Text changes
> Sync text and SelectedDate for DatePicker

- src/Runtime/Runtime/Runtime.OpenSilver.csproj
- src/Runtime/Runtime/System.Windows.Browser/WORKINPROGRESS/HtmlElement.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/TextBox.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/WORKINPROGRESS/DataGridColumn.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/WORKINPROGRESS/SpinDirection.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/WORKINPROGRESS/SpinEventArgs.cs
SpinDirection and one more file
> SpinDirection

- src/Runtime/Runtime/PublicAPI/Interop/HtmlPresenter.cs
> check for null

- src/Runtime/Runtime/DefaultStyles/INTERNAL_DefaultButtonStyle.xaml
- src/Runtime/Runtime/DefaultStyles/INTERNAL_DefaultDataGridStyle.xaml
- src/Runtime/Runtime/Runtime.CSHTML5.csproj
- src/Runtime/Runtime/Runtime.OpenSilver.csproj
- src/Runtime/Runtime/Themes/generic.xaml
- src/Runtime/Runtime/Windows.UI.Xaml.Controls.Primitives/Selector.cs
1. Added default style for DataGridColumnHeader.
2. Improved the default style of Button.
3. Fixed a minor issue in Selector.
> Styles improvement.

- src/Runtime/Runtime/Windows.UI.Xaml.Media/VisualTreeHelper.cs
Implemented the VisualTreeHelper.GetOpenPopups method.
> Implemented the VisualTreeHelper.GetOpenPopups method.

- src/Runtime/Runtime/Runtime.OpenSilver.csproj
- src/Runtime/Runtime/System.ServiceModel.Channels/WORKINPROGRESS/IPollingDuplexListenerSettings.cs
- src/Runtime/Runtime/System.ServiceModel.Channels/WORKINPROGRESS/IPollingDuplexSettings.cs
- src/Runtime/Runtime/System.ServiceModel.Channels/WORKINPROGRESS/PollingDuplexBindingElement.cs
- src/Runtime/Runtime/System.Windows.Interactivity/CustomPropertyValueEditor.cs
- src/Runtime/Runtime/System.Windows.Interactivity/CustomPropertyValueEditorAttribute.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Automation.Peers/WORKINPROGRESS/AutomationPeer.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Automation.Peers/WORKINPROGRESS/RangeBaseAutomationPeer.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Automation.Peers/WORKINPROGRESS/ScrollBarAutomationPeer.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Automation/WORKINPROGRESS/ElementNotAvailableException.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/WORKINPROGRESS/AutoCompleteBox.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/WORKINPROGRESS/Frame.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/WORKINPROGRESS/Page.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Documents/WORKINPROGRESS/Typography.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Navigation/WORKINPROGRESS/NavigationService.cs
- src/Runtime/Runtime/Windows.UI.Xaml/WORKINPROGRESS/FontCapitals.cs
Add "ElementNotAvailableException" class in WORKINPROGRESS
Add "ScrollBarAutomationPeer" class in WORKINPROGRESS
Add "PollingDuplexBindingElement" class in WORKINPROGRESS
Add "Typography" class in WORKINPROGRESS
Add "CustomPropertyValueEditor" into "System.Windows.Interactivity" namespace.
Add "ValueMemberBinding" property to the WORKINPROGRESS "AutoCompleteBox" class.
Add more stubs to the following WORKINPROGRESS classes: "Frame", "Page" and "NavigationService”.
Include the newlly added files into "Runtime.OpenSilver.csproj" file.
> Opened new pull request as the visual studio managed to break origin/develop

- src/Runtime/Runtime/System.ServiceModel/CSHTML5_ClientBase_1.cs
Handle the case when the FaultException detail type has it's DataConract namespace not set explicitly.
> Handle the case when the FaultException detail type has it's DataConract namespace not set explicitly.

- src/Runtime/Runtime/DefaultStyles/INTERNAL_DefaultContentControlStyle.xaml
- src/Runtime/Runtime/DefaultStyles/INTERNAL_DefaultDataGridStyle.xaml
- src/Runtime/Runtime/DefaultStyles/INTERNAL_DefaultTextBoxStyle.xaml
- src/Runtime/Runtime/Windows.UI.Xaml.Controls.Primitives/Selector.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/DataGrid.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/DataGridCell.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/TextBox.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Controls/WORKINPROGRESS/DataGridCellEditEndedEventArgs.cs
- src/Runtime/Runtime/Windows.UI.Xaml.Data/INTERNAL_PagedCollectionView.cs
- Improved DataGridColumnHeader style.
- TextBox style improvements.
- Fixed a small issue concerning the Label.
- Fixed DataGridCell alignment issue.
- Improved DataGridRow Selection and Alternating colors.
- Reverting ToggleButton style.
- Fixed issue: After removing DataGrid's last element on the 2nd page, the page doesn't change to the previous
> Made various improvements.

- src/Runtime/Runtime/Windows.UI.Xaml.Input/WORKINPROGRESS/FocusManager.cs
- src/Runtime/Runtime/Windows.UI.Xaml/UIElement_Events.cs
- src/Tests/Runtime.OpenSilver.Tests/Windows.UI.Xaml.Input/FocusManagerTest.cs
Implemented the FocusManager class.
> Implemented the FocusManager class.

- src/Simulator/Simulator/MainWindow.xaml.cs
- src/Simulator/Simulator/SimulatorLaunchParameters.cs
- src/Simulator/Simulator/SimulatorLauncher.cs
Now we can add custom code for the browser in the client's simulator
> Add access to the browser for the client's simulator

- src/Runtime/Runtime/Core/Events/INTERNAL_EventManager_2.cs
- src/Runtime/Runtime/Core/Rendering/INTERNAL_HtmlDomManager.cs
> Remove several dynamics

- src/Runtime/Runtime/System.Windows.Controls/Control.cs
- src/Runtime/Runtime/System.Windows.Media/Polygon.cs
Polygon Points
FontWeight Inheritance
> Fontweight & Polygon

- src/Runtime/Runtime/DefaultStyles/INTERNAL_DefaultScrollBarStyle.xaml
> fix scrollbar style

- src/VSExtension/OpenSilver.TemplateWizards/AppCustomizationWindow/AppConfigurationWindow.xaml
- src/VSExtension/OpenSilver.TemplateWizards/AppCustomizationWizard.cs
- src/VSExtension/OpenSilver.VSIX/source.extension.vsixmanifest
- src/VSExtension/OpenSilverApplicationTemplate/OpenSilverApplication.Browser/OpenSilverApplication.Browser.csproj
- src/VSExtension/OpenSilverApplicationTemplate/OpenSilverApplication.Browser/wwwroot/index.html
- src/VSExtension/OpenSilverClassLibraryTemplate/OpenSilverClassLibrary.csproj
- src/VSExtension/OpenSilverUwpApplicationTemplate/OpenSilverUwpApplication.Browser/OpenSilverUwpApplication.Browser.csproj
- src/VSExtension/OpenSilverUwpApplicationTemplate/OpenSilverUwpApplication.Browser/wwwroot/index.html
- src/VSExtension/OpenSilverUwpClassLibraryTemplate/OpenSilverUwpClassLibrary.csproj
> chore: move VSIX to dotnet6

- src/Runtime/Runtime/PublicAPI/Interop/INTERNAL_InteropImplementation.cs
The iterative approach to replace JavaScript arguments with the actual values can cause issues. For example if the second argument of JavaScript call is a string which contains "$0" then during the next iteration this "$0" will be replaced with wrong value.
Instead of replacing all arguments are collected in array and $0, $1 replaced with {0}, {1} ..., which later will be formatted by String.Format.
> Fixed JavaScript call arguments replacement

- src/Runtime/Runtime/System.Windows/LayoutManager.cs
- src/Runtime/Runtime/System.Windows/UIElement.cs
When scrolls down at DataGrid control, sometimes text was trimming at the end.
> Update on UI InvalidateArrange

- .github/workflows/github-actions.yml
This PR uncomments building of the simulator as a github action.
> Add building the simulator as a github action

- src/Runtime/Runtime/System.Windows/UIElement_Events.cs
Updated for the telerik controls (especially RadNumericUpdown)
> Raise the OnGotFocus or OnLostFocus after updating focused element.

- src/Runtime/Runtime/System.Windows.Controls/Control.cs
- src/Runtime/Runtime/System.Windows/UIElement_Events.cs
- src/Tests/Runtime.OpenSilver.Tests/System.Windows.Input/FocusManagerTest.cs
set the focused element on control focus
> fix: do not set focused element to null on lost focus

- src/Tests/TestApplication/TestApplication/Registry/TestRegistry.cs
- src/Tests/TestApplication/TestApplication/TestApplication.OpenSilver.csproj
- src/Tests/TestApplication/TestApplication/TestApplication.Silverlight.csproj
- src/Tests/TestApplication/TestApplication/Tests/ValidationSummaryTest.xaml
- src/Tests/TestApplication/TestApplication/Tests/ValidationSummaryTest.xaml.cs
A sample to demonstrate the issue about appearing "0 Errors" during rendering.
> chore: add ValidationSummary sample

- .github/workflows/github-actions.yml
Fix package downgrade detected issue
Sample build output:
https://github.com/pymendoza/OpenSilver/runs/4844448635?check_suite_focus=true
> chore: update nuget private package version suffix format

- src/Runtime/Runtime/System.Windows.Media/WORKINPROGRESS/Fonts.cs
Client REP implementation leftovers
> SystemTypefaces initialized

- src/Runtime/Runtime/DefaultStyles/INTERNAL_DefaultSliderStyle.xaml
- src/Runtime/Runtime/System.Windows.Controls/Slider.cs
Please don't look into it yet as I need to provide a description here.
> Enhancement: Slider updated to match default style and behavior as SilverLight.

- src/Runtime/Runtime/System.Windows.Browser/HtmlWindow.cs
- src/Runtime/Runtime/System.Windows.Browser/WORKINPROGRESS/ScriptObject.cs
Client REP implementation leftovers...
> ScriptObject.GetProperty() implementation

- .github/workflows/github-actions.yml
Allows us to use GitHub packages as a source of NuGet packages
> Upload packages to GitHub packages section

- src/Runtime/Runtime/System.Windows/FrameworkElement_HandlingSizeAndAlignment.cs
This reverts commit a4d58f22c09bb44a7aca83ac34219bf582c5d101.
> Revert "fix: fix nested Canvas layout issue (#328)"

- src/Runtime/Runtime/DefaultStyles/INTERNAL_DefaultProgressBarStyle.xaml
- src/Runtime/Runtime/Runtime.CSHTML5.csproj
- src/Runtime/Runtime/Runtime.OpenSilver.csproj
- src/Runtime/Runtime/System.Windows.Controls/ProgressBar.cs
- src/Runtime/Runtime/Themes/generic.xaml
Progressbar implemented with a default style
> feat: ProgressBar implemented with a default style

- src/Runtime/Runtime/System.Windows.Interactivity/TriggerBase.cs
- src/Runtime/Runtime/System.Windows.Interactivity/WORKINPROGRESS/EventTriggerBase.cs
DON'T get intimidated by the number of changes in this PR. The main change is fixing the EventTriggerBase.RegisterEvent() [line 455] to create delegates of the correct type; all the other changes are due to minor refactor like redundant **this** prefix removal, and exchanging fields for auto-properties...
> Event trigger fix 

- src/Runtime/Runtime/Runtime.OpenSilver.csproj
- src/Runtime/Runtime/System.Windows.Controls.Primitives/WORKINPROGRESS/Clipper.cs
- src/Runtime/Runtime/System.Windows.Controls.Primitives/WORKINPROGRESS/LinearClipper.cs
- src/Runtime/Runtime/System.Windows.Controls/WORKINPROGRESS/RangeTimePickerPopup.cs
- src/Runtime/Runtime/System.Windows.Controls/WORKINPROGRESS/Rating.cs
- src/Runtime/Runtime/System.Windows.Controls/WORKINPROGRESS/RatingItem.cs
- src/Runtime/Runtime/System.Windows.Controls/WORKINPROGRESS/ShortTimeFormat.cs
* clipper controls
* rating controls
* RangeTimePickerPopup
* ShortTimeFormat
> Add stubs for missing controls

- src/Simulator/Simulator/XamlInspection/XamlPropertiesPane.xaml
- src/Simulator/Simulator/XamlInspection/XamlPropertiesPane.xaml.cs
- src/Simulator/Simulator/XamlInspection/XamlSinglePropertyEditor.xaml.cs
Increased the margin for scrollViewer as the vertical scroll bar doesn't fully show
> feat: implement-one-Refresh-button-for-all-readonly-properties

- src/Runtime/Runtime/System.Windows/Window.cs
Added stub for the Show() method in the Window class
> chore: add stub for Window.Show()

- src/Compiler/Compiler/OtherHelpersAndHandlers/FixingServiceReferences.cs
- src/Runtime/Runtime/Runtime.CSHTML5.csproj
- src/Runtime/Runtime/Runtime.OpenSilver.csproj
- src/Runtime/Runtime/System.ServiceModel/WORKINPROGRESS/CSHTML5_DuplexClientBase.cs
- src/Runtime/Runtime/System.ServiceModel/WORKINPROGRESS/InstanceContext.cs
Added stubs for CSHTML5_DuplexClientBase which inherits from CSHTML5_ClientBase. Also added stubs for InstanceContaxt since it is used on DuplexClientBase.
> chore: add stub for CSHTML5_DuplexClientBase

- src/Runtime/Runtime/Runtime.OpenSilver.csproj
- src/Runtime/Runtime/System.Windows.Media/WORKINPROGRESS/VideoBrush.cs
added stub for the video brush class
> chore: add stub for VideoBrush

- src/Runtime/Runtime/Runtime.OpenSilver.csproj
- src/Runtime/Runtime/System.Windows.Controls/MediaElementState.cs
- src/Runtime/Runtime/System.Windows.Controls/WORKINPROGRESS/MediaElement.cs
- src/Runtime/Runtime/System.Windows.Media/TimelineMarkerCollection.cs
- src/Runtime/Runtime/System.Windows.Media/WORKINPROGRESS/TimelineMarker.cs
- src/Runtime/Runtime/System.Windows.Media/WORKINPROGRESS/TimelineMarkerCollection.cs
Added:
- Some MediaElement stubs & missing documentation ont he stubs that where already there
- MediaElementState enum
- TimelineMarker class stub
- TimelineMarkerCollection class stub
> chore: added missing stubs to MediaElement and some classes needed for it

- src/Runtime/Runtime/System.Net/WebClient.cs
- src/Runtime/Runtime/System.Windows.Controls/WORKINPROGRESS/MediaElement.cs
- src/Runtime/Runtime/System.Windows.Controls/WORKINPROGRESS/WebBrowser.cs
- src/Runtime/Runtime/System.Windows.Media.Animation/Storyboard.cs
- src/Runtime/Runtime/System.Windows/MessageBox.cs
Added stubs for: 
- WebClient.AllowReadStreamBuffering
- WebClient.IsBusy
- WebClient.CancelAsync
- WebClient.OpenReadAsync
- MediaElement.Stretch (and its dependecy property)
- WebBrowser.InvokeScript
- Storyboard.SeekAlignedToLastTick
- MessageBox.Show
> chore: add several stubs

- src/Runtime/Runtime/Core/Rendering/INTERNAL_VisualTreeManager.cs
fix nested Canvas layout issue, if we set position of stackpanel (child) as relative it works properly.
> fix nested Canvas layout issue

- src/Runtime/Runtime/Core/Main/INTERNAL_PropertyStore.cs
- src/Runtime/Runtime/System.Windows.Controls/Border.cs
- Fixed issue for gradient border.
Note: If any radius is used for border then browser is not supporting radius with border-image-source.
> Fix - border gradient issue in LinearGradientBrush

- src/Simulator/Simulator/MainWindow.xaml.cs
- src/Simulator/Simulator/SimulatorLaunchParameters.cs
I need to do some actions in simulator, but executed them after the app is started.
> Add callback parameter to call when the app is started in simulator

- src/Runtime/Runtime/System.Windows.Controls/TextBlock.cs
- src/Runtime/Runtime/System.Windows.Controls/TextBox.cs
- src/Runtime/Runtime/System.Windows.Controls/TextBoxView.cs
- src/Runtime/Runtime/System.Windows/LayoutManager.cs
- src/Runtime/Runtime/System.Windows/TextMeasurementService.cs
- src/Runtime/Runtime/System.Windows/UIElement.cs
- src/Runtime/Scripts/cshtml5.js
- Update TextBlock, TextBox measurement
- Force measurement if child needs invalidation
> Update TextBlock, TextBox measurement

- src/Compiler/Compiler/OtherHelpersAndHandlers/FixingServiceReferences.cs
Support for out parameters in web method
> Support for out parameters in web method

- src/Compiler/Compiler/6_CreatingAndCopyingSupportHtmlAndJavaScriptFiles/ExtractingAndCopyingResources.cs
- src/Targets/OpenSilver.Common.targets
* Fix generating `.g.js` files by replacing `Resource` to `EmbeddedResource` in `ResourcesProcessor` task
* Fix destination path for resources
After these changes `Application.GetResourceStream()` works correctly.
> Fix loading resources

- src/Targets/OpenSilver.Common.targets
to have ability to get resources using Assembly.GetManifestResourceStream()
> Do not remove resource files

- src/Runtime/Runtime/System.Windows.Controls/ProgressBar.cs
Progressbar keeps expanding on width.
[gif](https://media.giphy.com/media/6IhlqZRG0ztZ8G9G3W/giphy.gif)
This happens while creating an animation for file upload dialog.
The "Maximum" and the "Value" properties are binded to some data in background.
> UpdateProgressRectangle correct width

- src/Runtime/Runtime/System.Windows.Controls/TextBox.cs
> fix: TextBox-TextWrapping-default-value

- src/Runtime/Runtime/DefaultStyles/INTERNAL_DefaultDatePickerStyle.xaml
- src/Runtime/Runtime/DefaultStyles/INTERNAL_DefaultDatePickerTextBoxStyle.xaml
> fix: set opacity for disabled state of DatePicker

- src/Runtime/Runtime/System.Windows.Controls/ScrollViewer.cs
To test, after pull request https://github.com/OpenSilver/OpenSilver/pull/478 has been merged (so that a scrollbar with CustomLayout can be shown), go to the TestApplication -> AutoCompleteBox, filter the CustomLayout ACB so that enough items appear for the scrollbar to be shown.
> feat: enable mouse wheel scrolling on VirtualizedStackPanel

- src/Runtime/DataForm.Toolkit/DataField/DataField.cs
- src/Runtime/DataForm.Toolkit/DataForm/DataForm.cs
Recreated the PR, previous one had got build error from a unit test method
> perf: add ForceAlignment prop to align when needed

- src/VSExtension/OpenSilver.TemplateWizards/AppCustomizationWindow/AppConfigurationWindow.xaml
- src/VSExtension/OpenSilver.TemplateWizards/AppCustomizationWindow/AppConfigurationWindow.xaml.cs
- src/VSExtension/OpenSilver.TemplateWizards/AppCustomizationWindow/BlazorVersion.cs
- src/VSExtension/OpenSilver.TemplateWizards/AppCustomizationWizard.cs
- src/VSExtension/OpenSilver.VSIX/source.extension.vsixmanifest
- src/VSExtension/OpenSilverApplicationTemplate/OpenSilverApplication.Simulator/OpenSilverApplication.Simulator.csproj
- src/VSExtension/OpenSilverApplicationTemplate/OpenSilverApplication.vstemplate
- src/VSExtension/OpenSilverApplicationTemplate/OpenSilverApplication/OpenSilverApplication.csproj
I have not included nuget.config to this PR, I will send one more later.
> chore: replace .NET 5 by .NET 7 in vsix

- src/VSExtension/OpenSilver.TemplateWizards/AppCustomizationWizard.cs
- src/VSExtension/OpenSilver.VSIX/Nuget.Config
- src/VSExtension/OpenSilver.VSIX/OpenSilver.VSIX.csproj
- src/VSExtension/OpenSilver.VSIX/source.extension.vsixmanifest
I did not find a way to include Nuget.Config as a template item on the level of .sln file, so I have implemented this programmatically.
> Add nuget.config to VSIX

- src/Runtime/Runtime/System.Windows.Controls/Toolkit/CollectionHelpers.cs
- src/Runtime/Runtime/System.Windows/DataObject.cs
Prepare some missing stuff to support drag-and-drop in ListBox with ICollectionView
> Missing stuff for drag-and-drop

- src/Runtime/Runtime/System.Windows/Clipboard.cs
- src/Simulator/Simulator/Interop/ClipboardHandler.cs
> Clipboard Implementation

- src/Runtime/Runtime/Core/Events/DOMEventManager.cs
- src/Runtime/Scripts/cshtml5.js
Add the touch events only when device has touch support.
> Add the touch events only when device has touch support

- src/Runtime/Runtime/System.Windows.Data/CollectionViewSource.cs
Collection view was not being sorted if add SortDescription before setting the Source property
Sample branch: https://github.com/avdynut/SL_OS_Test/tree/collection-view-sorting
> Fix collection view sorting

- src/VSExtension/OpenSilver.TemplateWizards/AppCustomizationWizard.cs
- src/VSExtension/OpenSilver.VSIX/source.extension.vsixmanifest
Visual Studio passes the wrong value :(
> Workaround for copying nuget.config

- src/Runtime/Runtime/OpenSilver/Controls/OpenFileDialog.cs
- src/Runtime/Runtime/OpenSilver/IO/MemoryFileInfo.cs
> OpenFileDialog Stubs

- src/Runtime/Runtime/System.Windows.Shapes/Shape.cs
> ImageBrush Support in Shape

- src/Runtime/Controls.Data/DataGrid/DataGrid.xaml.cs
- src/Runtime/Runtime/System.Windows.Controls/Canvas.cs
- src/Runtime/Runtime/System.Windows.Controls/Grid.cs
- src/Runtime/Runtime/System.Windows.Controls/StackPanel.cs
- src/Runtime/Runtime/System.Windows/FrameworkElement.cs
- src/Runtime/Runtime/System.Windows/FrameworkElement_HandlingSizeAndAlignment.cs
- src/Runtime/Runtime/System.Windows/LayoutManager.cs
- src/Runtime/Runtime/System.Windows/UIElement.cs
- When CustomLayout root is taking DeferredRendering, InvalidateMeasure was not working.
- Fix when root has margin values.
> Fix customlayout

- src/Runtime/Runtime/System.Windows.Media/VisualTreeHelper.cs
Fix FindElementsInHostCoordinates to get the relavent elements
> Fix FindElementsInHostCoordinates to get the relavent elements

- src/Runtime/Runtime/System.Windows.Controls/PasswordBoxView.cs
fix: apply foreground color  on password box
> fix: apply foreground color  on password box

- src/Runtime/Scripts/OpenSilver.js
Use ?date=<date> when loading js/css files to not use the cached versions.
> Use date when loading js/css files

- src/Runtime/Controls.Data/DataGrid/DataGridRows.cs
- src/Runtime/Runtime/Core/Rendering/INTERNAL_VisualTreeManager.cs
- src/Runtime/Runtime/OpenSilver/Internal/Xaml/RuntimeHelpers.cs
- src/Runtime/Runtime/System.Windows/Settings.cs
- src/Runtime/Runtime/System.Windows/UIElement.cs
It just progressively loads (if enabled) rows in chunks than loading all in one go, please take a look at this [video](https://drive.google.com/file/d/1-F22uBPHf65EppHGJUBdQcchtryoU-Ne/view?usp=sharing).
> DataGrid Enhancement: Progressive Loading Implemented

- src/Runtime/Runtime/System.Windows.Controls/TextBoxView.cs
> Fix changing ReadOnly property for TextBox

- src/Runtime/Runtime/DefaultStyles/INTERNAL_DefaultContentControlStyle.xaml
Having `VerticalScrollBarVisibility = Visible` is causing many issues for TextBox, DatePicker and other controls.
> Change back ScrollBarVisibility to Auto

- src/Runtime/Runtime/System.Windows.Controls/RichTextBox/RichTextBox.cs
- src/Runtime/Runtime/System.Windows.Controls/RichTextBox/RichTextFormatParser.cs
- process missing inlines
- process children of Span inline
- process plain text node
- handle null inlines
- fix setting font size and adding line break
- refactoring
> Improve RichTextBox

- src/Runtime/Runtime/System.Windows.Controls/Viewbox.cs
Added MeasureOverride and ArrangeOverride in ViewBox
> Added MeasureOverride and ArrangeOverride in ViewBox

- src/Runtime/Runtime/DefaultStyles/INTERNAL_DefaultScrollBarStyle.xaml
- Fixes an issue where implicit styles of Button defines on application would apply to the style of the ScrollBar. (client_PUL) 
- Enable auto scroll when holding the button.
- Closer to original SL template.
> fix : change Button to RepeatButton in ScrollBar template like SL

- src/Runtime/Runtime/System.Windows.Controls/ComboBox.cs
> fix: combo box overflowing text

- .github/workflows/validate-prs.yml
* adjust configuration
* handle resource extractor
* copy targets
* rebuild simulator
> Update pr validator according to the latest changes in the compiler

- src/Runtime/Runtime/System.ServiceModel/CSHTML5_ClientBase_1.cs
> WCF: Support MessageContract responses

- src/Runtime/Runtime/System.Windows.Shapes/Shape.cs
The current implementation fails for this case:
`
<Rectangle x:Name="MyRectangle" Width="0" Height="0">
<Rectangle.Fill>
<LinearGradientBrush StartPoint="0,0" EndPoint="1,1" SpreadMethod="Repeat">
<GradientStop Color="Red" Offset="0.0" />
<GradientStop Color="Blue" Offset="0.5" />
<GradientStop Color="Green" Offset="1.0" />
</LinearGradientBrush>
</Rectangle.Fill>
</Rectangle>
`
Furthermore, this example is available there - https://github.com/jacob-l/OpenSilverLinearGradientBrush
> Handle zero width and height for linear gradient brush

- src/Runtime/Controls.Data/DataGrid/DataGridColumnHeader.xaml.cs
> Fixed DataGrid column reordering

- src/Runtime/Runtime/Core/WebRequestHelper/INTERNAL_WebRequestHelper_JSOnly.cs
- src/Runtime/Runtime/System.ServiceModel/CSHTML5_ClientBase_1.cs
Example is available here - https://github.com/jacob-l/OpenSilverFaultException
> Throw FaultException for WCF Soap calls

- src/Runtime/Runtime/System.Windows.Media/LinearGradientBrush.cs
Use the same code to draw gradients in browser and simulator.
> fix: unified approach to gradient drawing in Browser and Simulator

- src/Runtime/Runtime/DefaultStyles/INTERNAL_DefaultBusyIndicatorStyle.xaml
- src/Runtime/Runtime/System.Windows.Controls/WORKINPROGRESS/BusyIndicator.cs
Correction of BusyIndicator Styles
> Correction of BusyIndicator Styles

- src/Runtime/Runtime/OpenSilver/IO/MemoryFileInfo.cs
Support for Length property in memoryfileinfo
> Support for Length property in memoryfileinfo

- src/Compiler/Compiler.ResourcesExtractor/Helpers/ResourcesExtractor.cs
- src/Compiler/Compiler.ResourcesExtractor/Tasks/ResourcesExtractorAndCopier.cs
- src/Compiler/Compiler/OtherHelpersAndHandlers/Version.cs
- src/Compiler/Tests/Compiler.Tests/MonoCecilAssembliesInspectorTest.cs
- src/Compiler/Tests/Compiler.Tests/ResourcesExtractor/ResourcesExtractorTest.cs
- src/Targets/OpenSilver.Common.targets
- src/Targets/OpenSilver.Simulator.targets
Currently only limited set of extensions is supported to be added to application resources
> Support all types of files except of xaml in resources

- src/Runtime/OpenSilver.Xaml/System.Xaml/XamlObjectWriter.cs
- src/Runtime/Runtime/System.Windows.Documents/InlineCollection.cs
- src/Runtime/Runtime/System.Windows.Documents/TextElementCollection_1.cs
Support for Inline Text in XamlReader
- Sample
<Canvas x:Name="LayoutRoot" Background="White" Width="675" Height="500" 
xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" >    
<ScrollViewer Width="675" Height="500" >    
<StackPanel Orientation="Vertical">        
<Border>            
<TextBlock TextWrapping="Wrap" FontWeight="Bold" FontSize="16" Height="Auto">Test</TextBlock>        
</Border>  
</StackPanel>    
</ScrollViewer>
</Canvas>
> Support of Inline text in textblock.

- src/Simulator/Simulator/MainWindow.xaml.cs
Handle resource path with space.
> Handle resource path with space.

- src/Runtime/Runtime/System.Windows.Threading/Dispatcher.cs
- src/Tests/Runtime.OpenSilver.Tests/System.Windows.Media/CompositeTransformTest.cs
- src/Tests/Runtime.OpenSilver.Tests/System.Windows.Media/MatrixTest.cs
Refactored Dispatcher to have distinct implementations for Browser and Simulator.
> feat: separate Dispatcher implementation for Browser and Simulator environments

- src/Runtime/Runtime/System.Windows.Controls/MediaElement.cs
- src/Runtime/Runtime/System.Windows.Controls/WORKINPROGRESS/MediaElement.cs
Provided support for MediaOpen and MediaEnded event
> feat:Implement MediaOpen and MediaEnded event support.

- src/Maui/Hybrid/Threading/BackgroundThreadSynchronizationContext.cs
- src/Maui/Hybrid/wwwroot/libs/mauihybrid.js
- src/Runtime/Runtime/Properties/AssemblyInfo.cs
> Increase required XAML Designer version

- src/Runtime/Runtime/System.Windows.Controls/InkPresenter.cs
Also prevent cleaning the canvas after resizing
> Ability to change line width and color of stroke in InkPresenter

- src/Runtime/Runtime/System.Windows.Controls/InkPresenter.cs
Make InkPresenter more similar to Silverlight:
https://github.com/user-attachments/assets/95e4a5fa-d33a-4db1-b11d-468b57cdd9e0
> InkPresenter: ability to draw one point, make strokes rounded
