OpenSilver/OpenSilver

src/CSHTML5.Runtime/PublicAPI/Native.Html.Controls/TextElement.cs
See http://forums.cshtml5.com/viewtopic.php?f=4&t=8575
Implement FontWeight in TextElement to format Javascript font string correctly
Change to ActualWidth to calculate the effect of FontHeight (but not FontWeight)
=> Implemented FontWeight in TextElement

src/Runtime/Runtime/Windows.UI.Xaml.Controls/AutoCompleteBox.cs, src/Runtime/Runtime/Windows.UI.Xaml.Controls/DataGridRow.cs
According to [this](https://docs.microsoft.com/en-us/previous-versions/windows/silverlight/dotnet-windows-silverlight/dd459699(v=vs.95)) DropDownClosed event is RoutedPropertyChangedEventHandler<bool> for Silverlight.
And DataGridRow [derives](https://docs.microsoft.com/en-us/previous-versions/windows/silverlight/dotnet-windows-silverlight/cc189610(v=vs.95)) from Control
=> Adjust types

src/Runtime/Runtime/PublicAPI/Interop/INTERNAL_JSObjectReference.cs
For example, we get callback parameters in the format {0: '2020', 1: '12', 2: '15'} instead of array.
=> Handle callback parameters

src/Runtime/Runtime/Microsoft.Expression.Interactivity.Core/WORKINPROGRESS/ControlStoryboardAction.cs, src/Runtime/Runtime/System.Windows.Media.Effects/WORKINPROGRESS/PixelShader.cs, src/Runtime/Runtime/System.Windows.Media.Effects/WORKINPROGRESS/ShaderEffect.cs, src/Runtime/Runtime/Windows.UI.Xaml.Controls/TextBox.cs, src/Runtime/Runtime/Windows.UI.Xaml.Controls/WORKINPROGRESS/VirtualizingStackPanel.cs, src/Runtime/Runtime/Windows.UI.Xaml.Media.Animation/WORKINPROGRESS/PointAnimation.cs, src/Runtime/Runtime/Windows.UI.Xaml.Media/WORKINPROGRESS/ImageBrush.cs, src/Runtime/Runtime/Windows.UI.Xaml.Media/WORKINPROGRESS/TileBrush.cs, src/Runtime/Runtime/Windows.UI.Xaml.Shapes/Shape.cs
Some dependency properties configured with the incorrect CLR "wrapper' properties names. Some CLR "wrapper" properties use the incorrect dependency property as a backing field in their getters/setters. The `nameof` directive used instead of the hardcoded constants for referencing the CLR "wrapper" properties names and preventing such a problem in the future.
=> Fixed problems in several `DependencyProperty.Register` calls found by the PVS-Studio static code analyzer

src/Runtime/Runtime/Core/Events/INTERNAL_EventManager_2.cs, src/Runtime/Runtime/Core/Events/INTERNAL_EventsHelper.cs, src/Runtime/Runtime/Core/Main/INTERNAL_SimulatorExecuteJavaScript.cs, src/Runtime/Runtime/PublicAPI/Native.Html.Controls/ContainerElement.cs, src/Runtime/Runtime/PublicAPI/Native.Html.Controls/HtmlCanvas.cs, src/Runtime/Runtime/PublicAPI/Native.Html.Controls/ImageElement.cs, src/Runtime/Runtime/PublicAPI/Native.Html.Controls/RectangleElement.cs, src/Runtime/Runtime/PublicAPI/Native.Html.Controls/TextElement.cs, src/Runtime/Runtime/System.IO.IsolatedStorage/IsolatedStorageSettings.cs, src/Runtime/Runtime/System.ServiceModel/CSHTML5_ClientBase_1.cs, src/Runtime/Runtime/Windows.UI.Xaml.Data/ListCollectionView.cs, src/Runtime/Runtime/Windows.UI.Xaml.Media.Animation/RepeatBehavior.cs, src/Runtime/Runtime/Windows.UI.Xaml/Content.cs, src/Runtime/Runtime/Windows.UI.Xaml/UIElement_Events.cs
Lots of easy-to-fix issues in XML comments for reducing the number of warnings generated during the full build.
=> Fixed minor problems (warnings) in XML comments found by the C# compiler during the full rebuild

src/Runtime/Runtime/Windows.UI.Xaml.Controls/Image.cs
When Silverlight can not show an image it shows nothing. In the browser, we see a broken image icon in this case.
We have several possible reasons:
1. We did not specify the source: <Image />
2. The Source == null
3. We can not load image
=> Prevent broken image icon in the browser

src/Targets/OpenSilver.Common.targets
1. .netStandard 2.1 and .net6 uses different output for browser project. There are two new properties to use different paths according to current target framework
2. Changes condition to run extracting resources only for the Browser project.
=> Change the folder with assemblies for extracting resources

src/Runtime/Runtime/Core/Rendering/INTERNAL_VisualTreeManager.cs
Inverted the order in which elements are detached from the DOM (before it was Parent -> Child Now it is Child -> Parent)
=> Fixed element not found js issue on visual children detachment.

src/Runtime/Runtime/Windows.UI.Xaml.Controls.Primitives/Selector.cs
When ListBox ItemsSource is PagedCollectionView then CurrentChanged event is never being called.
=> Call MoveCurrentToPosition if selected item is changed

src/Runtime/Runtime/DefaultStyles/INTERNAL_DefaultContentControlStyle.xaml, src/Runtime/Runtime/Windows.UI.Xaml.Controls/Control.cs
- Set Inherits=True for Control FontSize to measure TextBlock size correctly
- Update CheckBox template to avoid interop calls for GetActualWidthAndHeight
=> Inherits FontSize for textmeasurement, update CheckBox Template

src/Runtime/Runtime/Runtime.CSHTML5.csproj, src/Runtime/Runtime/System.Windows.Browser/HtmlPage.cs
For now it does not cover all scenarios. For instance, we can only pass primitive types, which are supported by OpenSilver.
Also, we can not get the result of the method execution, because our execution engine is async.
=> Allows to call the scriptable members

src/Runtime/Runtime/System.Windows.Controls/Grid.cs
Currently it's disabled under Custom Layout.
For CSS style layout, please check line 158.
=> Disable css layout of the grid when CustomLayout is enabled

src/Runtime/Runtime/System.Windows.Controls/TextBoxView.cs
The check prevents entering text when MaxLength is set and the text is selected.  It just needs to remove the selected part and add a new entered symbols instead.
=> Allow adding text if there was a selection

src/Runtime/Runtime/System.Windows/DependencyObjectCollection_1.cs
DependencyObjectCollection.Add was raising OnCollectionChanged with wrong index during Add
=> Fix: Invalid index issue at raising OnCollectionChanged event in DependencyObjectCollection.Add

src/Targets/OpenSilver.Common.targets
Now the separate g.cs files are generated for the first step and for the second.
=> fix: split compilation of g.cs into two: for first step and for second

src/Runtime/Runtime/PublicAPI/Interop/INTERNAL_InteropImplementation.cs, src/Tests/Runtime.OpenSilver.Tests/OpenSilver/ReplaceArgsTest.cs
`String.Format` is known to be a slow function. Taking into account also that `ExecuteJavaScript_SimulatorImplementation` function is called tens of thousands times it will be beneficial to just replace all arguments in one iteration.
=> Added function to replace javascript arguments

src/Runtime/Runtime/Core/Other/INTERNAL_ShapesDrawHelpers.cs, src/Runtime/Runtime/System.Windows.Shapes/Path.cs
The solution is to provide the required size information in MeasureOverride. Also marking measure invalidate (InvalidateMeasure) once Data property is changed for Path.
Also refactored INTERNAL_ShapesDrawHelpers.PrepareStretch to use Shape as argument as we need StrokeThickness there and also because this class is ideally be used with Shape's descendent (Line, Ellipse, Rectangle, Path) classes.
=> Path's MeasureOverride implemented to return size of the path.

src/Runtime/Runtime/System.Windows.Controls/TextBox.cs, src/Runtime/Runtime/System.Windows.Controls/TextBoxView.cs
`var textbox = new TextBox() {Text = "Test", TextAlignment = TextAlignment.Right};`
For example,  in the above sample, text-alignment would not take effect. This PR is about fixing that.
=> Fix: TexBox.TextAlignement is not setting on creation

src/Runtime/Scripts/cshtml5.js
Prevent generating warnings in the browser every second.
=> touchstart, wheel and touchmove events marked as passive

src/Runtime/Controls.Data.Input/themes/generic.xaml
This PR shows an error block with errors instead of hiding when there is no error.
=> Prevent showing "0 errors" red block during rendering

src/Runtime/DataForm.Toolkit/themes/generic.xaml
Storyboard starts the animation when the page is fully loaded. So setting CommitButton or CancelButton visibility to Collapsed never works because storyboard set's the visibility back to Visible.
=> Fix DataForm buttons visibility

.github/workflows/validate-prs.yml
It is the first step in the validation of PRs.
For now it includes actions to verify that SL and UWP versions of OpenSilver can be built successfully.
=> Add validations for PRs

build/build-nuget-package-OpenSilver-private.bat, build/build-nuget-package-OpenSilver.Simulator-private.bat, build/build-nuget-package-OpenSilver.Simulator.bat, build/build-nuget-package-OpenSilver.bat, build/nuspec/OpenSilver.Simulator.nuspec, build/nuspec/OpenSilver.nuspec
Add repository URL as a parameter to the nuspec file.
Adjust building process to use nuget.exe for the simulator.
=> Add repository url to nuspec

src/Runtime/Runtime/System.Windows.Controls/TextBox.cs
When there is a ScrollViewer in the template of component, then editable div does not fill all space. If a user clicks on the ScrollViewer then the component does not get focus.
For example, if the template looks like:
```
<Style TargetType="TextBox">
<Setter Property="BorderThickness" Value="1"/>
<Setter Property="Background" Value="#FFFFFFFF"/>
<Setter Property="Foreground" Value="#FF000000"/>
<Setter Property="Padding" Value="2"/>
<Setter Property="BorderBrush" Value="#FF718597" />
<Setter Property="Template">
<Setter.Value>
<ControlTemplate TargetType="TextBox">
<Border x:Name="OuterBorder"
Background="{TemplateBinding Background}"
BorderBrush="{TemplateBinding BorderBrush}"
BorderThickness="{TemplateBinding BorderThickness}">
<ScrollViewer>
<ContentPresenter x:Name="ContentElement" …
```
=> Pass focus to TextBoxView in the TextBox

src/Runtime/Runtime/PublicAPI/Interop/Interop.cs, src/Runtime/Runtime/PublicAPI/Native.Html.Printing/PrintManager.cs
PrintManager  and Interop.GetDiv were using FrameworkElement just to get the INTERNAL_Outer/InnerDomElement prop. Used UIElement there as those properties are in UIElement
=> Refactor: Reference UIElement in place of FrameworkElement where Inner/Outer dom is used

src/Compiler/Compiler/OtherHelpersAndHandlers/ReflectionOnSeparateAppDomainHandler.cs
There was a NullReferenceException if compiling XAML with non-existing value in a enum property
=> Throw exception if enum value is not found in xaml

src/Runtime/Runtime/System.Windows/Settings.cs, src/Runtime/Runtime/System.Windows/WORKINPROGRESS/Application.cs
`IsRunningOutOfBrowser` property is not implemented and always returns `false`. In my project, I have many places with checking the value of the property. So it would be useful to have the ability to set this property somewhere in application startup as I can do for `HasElevatedPermissions `property
=> Add ability to set value of IsRunningOutOfBrowser property

src/Simulator/Simulator/MainWindow.xaml.cs
It saves the current rendered html in a file with time stamp
can pass html id, or xaml element name to only save this element's tree
(observation) : If it's called on the same stack frame more than once, it disrupts the app threads and ends the app
=> feat: Simulator; Implement SaveHtmlSnapshot

src/Runtime/Runtime/Runtime.OpenSilver.csproj, src/Runtime/Runtime/System.Windows.Controls/DragDropEffects.cs, src/Runtime/Runtime/System.Windows.Controls/DragDropKeyStates.cs, src/Runtime/Runtime/System.Windows.Controls/DragDropTarget_2.cs, src/Runtime/Runtime/System.Windows.Controls/DragEventArgs.cs, src/Runtime/Runtime/System.Windows.Controls/ItemDragEventArgs.cs
I need to use package with 'unsupported' constant to successfully compile a project. For example to use all values from DragDropEffects enum.
Anyway what is the purpose of this constant?
=> Define 'unsupported' constant

src/Runtime/Runtime/System.Windows.Controls/DatePicker.cs
Clearing datepicker when the value is not a date doesn't clear the textbox 
example :
xaml : 
<DatePicker x:Name="datepicker" />
<Button Grid.Row="1" Content="Clear" Click="Button_Click" />
c#:
private void Button_Click(object sender, RoutedEventArgs e)
{
datepicker.SelectedDate = null;
}
=> Clear text for datepicker when the value is not a date

src/Runtime/Runtime/PublicAPI/Interop/INTERNAL_InteropImplementation.cs, src/Runtime/Runtime/PublicAPI/Interop/INTERNAL_JSObjectReference.cs, src/Runtime/Runtime/PublicAPI/Interop/OnCallBack.cs, src/Runtime/Runtime/Runtime.CSHTML5.csproj, src/Runtime/Runtime/System.Windows.Controls/Grid_InternalHelpers.cs, src/Runtime/Runtime/System.Windows.Controls/TextBoxView.cs, src/Simulator/Simulator/MainWindow.xaml.cs, src/Tests/Runtime.OpenSilver.Tests/CSHTML5.Types/INTERNAL_JSObjectReferenceTest.cs
This PR fixes passing parameters to callback. Small example:
```
OpenSilver.Interop.ExecuteJavaScript(
"setTimeout(function () { $0(true); }, 1)",
(Action<bool>)(par =>
{
Console.WriteLine("PARAMETER - " + par);
}));
```
=> fix: handle JsonElement parameters for callbacks

src/Compiler/Compiler/2_ConvertingXamlToCSharp/GettingInformationAboutAXamlType.cs
DomainDataSource type in System.Windows.Controls.DomainServices
was being expected in the OpenSilver.dll
=> fix: assemblyName and namespace for openria in xaml (DomainDataSource)

src/Runtime/Runtime/Core/Main/INTERNAL_Simulator.cs, src/Runtime/Runtime/System.Windows.Threading/CoreDispatcher.cs, src/Simulator/Simulator/Interop/InteropHelpers.cs, src/Simulator/Simulator/MainWindow.xaml.cs
Dispatcher.CheckAccess() now returns actual value if run under Simulator.
Setting UI controls from others threads than the main thread, caused javascript errors in simulator.
=> Implement CheckAccess() for simulator

src/Runtime/Runtime/System.Windows/TextMeasurementService.cs, src/Runtime/Runtime/System.Windows/Window.cs
Some pages in our project contain a lot of UI controls, so they are placed inside ScrollViewer. But scrolling is not working properly.
The root div of OpenSilver html page contains style with `display:table` property. If remove it, scrolling is working.
This property is set in `FrameworkElement.INTERNAL_ApplyVerticalAlignmentAndHeight()`, because there are hidden TextBlock and TextBox elements inside the main div and we have default styles for these controls with
`<Setter Property="VerticalAlignment" Value="Center" />`
The issue also can be reproduced with value `Bottom`.
=> Fix content scrolling if there is default style for text control with VerticalAlignment

src/Runtime/Runtime/DefaultStyles/INTERNAL_DefaultComboBoxStyle.xaml
Hi difference between enabled and disabled. 
Before
After
=> fix: set opacity for disabled state of combobox

.github/workflows/github-actions.yml, .github/workflows/validate-prs.yml
We can not use the latest .NET 6.0.3 because it requires msbuild 17, which is not available for windows-2019 image.
I have hardcoded .NET 6.0.202 while we wait the response for this [issue](https://github.com/actions/virtual-environments/issues/5522).
BTW, We can not easily move to windows-2022 because it does not support .Net Framework 4.6, which is used by our Simulator.
For other projects I suggest to move to windows-2022.
=> fix: force to use previous version of .NET framework

src/Runtime/Controls.Input/AutoCompleteBox/PopupHelper.cs, src/Runtime/Controls.Input/Themes/generic.xaml, src/Runtime/Runtime/System.Windows/FrameworkElement_HandlingSizeAndAlignment.cs, src/Tests/TestApplication/TestApplication/Tests/AutoCompleteBoxTest.xaml, src/Tests/TestApplication/TestApplication/Tests/AutoCompleteBoxTest.xaml.cs
When using IsAutoWidthOnCustomLayout or IsAutoHeightOnCustomLayout=True, controls can have sizes that are larger than the Window boundaries. This will lead to poor performance, since ScrollViewers are not triggered. This change takes the Window ActualHeight and ActualWidth into account on the available size for Measure().
This also makes  IsAutoWidthOnCustomLayout and IsAutoHeightOnCustomLayout DependencyProperties, and add them (along with CustomLayout) as Template Binding for AutoCompleteBox. This way, setting these properties on the ACB will reflect on the Selector part of the ControlTemplate (the ListBox on the DropDown).
To test, you can open the TestApplication and go to the AutoCompleteBox section. There will be a CustomLayout ACB. Before this change, the dropdown would not have a …
=> Limit IsAutoWidth/HeightOnCustomLayout to Window boundaries

src/Runtime/Controls.Input/AutoCompleteBox/AutoCompleteBox.cs, src/Runtime/Runtime/System.Windows.Controls.Primitives/ScrollBar.cs
After https://github.com/OpenSilver/OpenSilver/pull/478 is merged, this can be tested by going to the TestApplication -> AutoCompleteBox, filtering the CustomLayout ACB to have a ScrollBar appear and do a scroll with mouse drag.
=> fix: correct MouseLeftUp on AutoCompleteBox ScrollBar closing dropdown

src/Runtime/Controls.Data/Extensions.cs
`GetItemType()` was returning null if the source list is empty `CollectionView`
In our project we use `ICollectionView` as `DataGrid ItemsSource`. In this case every time we call `ICollectionView.Refresh()` method, rows and columns are fully regenerated. Because `DataGridDataConnection.DataType` is null.
This commit fixes this and `ICollectionView.Refresh()` reloads only rows, it improves DataGrid performance
=> Fix getting item type for CollectionView

src/Runtime/Runtime/DefaultStyles/INTERNAL_DefaultHyperlinkButtonStyle.xaml
- unite underlined and disabled textblock
- replace rectangle with border
HyperlinkButton looks the same as before, but creating controls is 10-20% faster
=> Optimize visual tree of HyperlinkButton

src/Runtime/Runtime/System.Windows.Controls/Grid_InternalHelpers.cs
` <RowDefinition Height="Auto" MinHeight="35" />`
Silverlight and CSS grid, both have support for multiple sizing units where we can have a row with automatic height and at the same time, it respects a minimum height.
=> feat: Added support for two size units in grid row

src/Runtime/Controls.Input/AutoCompleteBox/AutoCompleteBox.cs
This can be tested on the TestApplication -> AutoCompleteBox.
Leaving a comment to signal that if tab order/behavior matches Silverlight in the browser, this manual handling of the Tab key might be able to be removed.
=> fix: enable closing AutoCompleteBox dropdown with the Tab key

src/Runtime/Runtime/DefaultStyles/INTERNAL_DefaultScrollBarStyle.xaml, src/Tests/TestApplication/TestApplication/Tests/AutoCompleteBoxTest.xaml, src/Tests/TestApplication/TestApplication/Tests/AutoCompleteBoxTest.xaml.cs
When scrolling on a CustomLayout ScrollBar (especially with higher speeds), the background buttons (LargeDecrease and LargeIncrease) can overflow and overlap with the navigation buttons (SmallDecrease and SmallIncrease), until they rendered again by the layout update.
This change moves the background buttons to the back in the ScrollBar style order, to guarantee that they will always have a higher VisualLevel then the Thumb and the navigation buttons.
To test this, go to the TestApplication -> AutoCompleteBox and filter the CustomLayout ACB to make the dropdown have a CustomLayout ScrollBar.
=> Fix CustomLayout ScrollBar background overlapping with navigation buttons

src/Runtime/Runtime/System.Windows.Controls/ComboBox.cs
Just like list box and auto complete box, virtualization can now be enabled in combo box from control itself using customlayout property. no need to add style and template for it,
=> fix: Combobox virtualization can be enabled without defining style and template

src/Runtime/Runtime/System.Windows.Controls/ToolTip.cs, src/Runtime/Runtime/System.Windows.Controls/VisualStates.cs
ToolTip is now handling the visual state changes for the cases in ContentControl (INTERNAL_DefaultContentControlStyle.xaml), TextBox (INTERNAL_DefaultTextBoxStyle.xaml), ListBox (INTERNAL_DefaultListBoxStyle.xaml), TreeView/TreeViewItem (INTERNAL_DefaultTreeViewItemStyle.xaml/INTERNAL_DefaultTreeViewStyle.xaml), Common Error validation (first ToolTip style in common.xaml) and if specified in custom-style in client projects.
=> ToolTip switches to states when IsOpen is changed

src/Runtime/Runtime/System.Windows.Controls/Grid.cs, src/Runtime/Runtime/System.Windows.Controls/TextBlock.cs, src/Runtime/Runtime/System.Windows/FrameworkElement.cs, src/Runtime/Scripts/cshtml5.js
- textblock measurement was not correct when the text is empty
- textblock should be centered when the parent element width is smaller than the text width
=> fix textblock measurement, arrangement

src/Runtime/Runtime/System.Windows.Controls/Control.cs, src/Runtime/Runtime/System.Windows.Controls/Validation.cs, src/Runtime/Runtime/System.Windows/UIElement.cs
[This PR](https://github.com/OpenSilver/OpenSilver/pull/522) implements validation for Binding.ValidatesOnNotifyDataErrors, with the changes from there, we see double validation tooltips in a control ([try this project](https://github.com/avdynut/OpenSilverValidation.git) to see the issue, this PR fixes that issue (please review/merge this PR once done with 522).
Usually, every input control should have invalidFocused/invalidUnfocused states which has the template for validation tooltips, for example, [the TextBox style](https://github.com/OpenSilver/OpenSilver/blob/6860c819de80317d9fc3bde371ebf279f92c546b/src/Runtime/Runtime/DefaultStyles/INTERNAL_DefaultTextBoxStyle.xaml#L139) has that set which is showing/hiding from [Control.UpdateValidationState](https://github.com/OpenSilver/OpenSilv …
=> Fix: Fixed double validation tooltips showing issue

src/Compiler/Compiler/2_ConvertingXamlToCSharp/GeneratingCSharpCode.Pass2.cs, src/Compiler/Compiler/2_ConvertingXamlToCSharp/GeneratingCSharpCode.cs
The Compiler used to look for elements named ResourceDictionary, now it
also accepts subclasses.
=> feat: handle ResourceDictionary subclasses in XAML

src/Runtime/Runtime/System.Windows.Media.Effects/WORKINPROGRESS/ShaderEffect.cs, src/Runtime/Runtime/System.Windows/DependencyObjectCollection_1.cs, src/Tests/Runtime.OpenSilver.Tests/System.Windows/DependencyObjectCollectionTest.cs
Registered a DependencyProperty on ShaderEffect to solve a null reference, and handled the case where IndexOf should return -1 on DependencyObjectCollection (added a unit test for this).
=> fix: return -1 on IndexOf of DependencyObjectCollection when item does not exist

src/Runtime/Runtime/System.Windows/FrameworkElement.cs
When parent width is narrow than the child, HorizontalAlignment=Stretch  should work as Left alignment.
Similarly, VerticalAlignment=Stretch should same with Top Alignment.
=> Custom layout: fix alignment when parent size is smaller than the child.

src/Runtime/Runtime/System.Windows.Shapes/Line.cs, src/Runtime/Runtime/System.Windows.Shapes/Polyline.cs, src/Runtime/Runtime/System.Windows.Shapes/Shape.cs
1) Fixed: Polyline.Points binding was not working, 
2) Gracefully resolved Line.MeasureOverride was throwing exception (in Size) due to negative size
=> Fix: Polyline.Points binding was not working

src/Runtime/Runtime/System.Windows.Controls/TextBox.cs
SelectionStart was always null if in the handler of TextChanged event.
=> Fixe: SelectionStart was always zero in TextChanged event

src/Runtime/Runtime/System.Windows.Controls/Viewbox.cs, src/Runtime/Runtime/System.Windows.Controls/WORKINPROGRESS/DatePicker.cs
In ALY project, we are getting these two exceptions
1) DatePicker : Not necessarily needed to throw.
2) ViewBox: ChildElement was not sometime and was causing exception in applytemplate.
=> Fix: two exceptions related to ViewBox and DatePicker

src/Runtime/Runtime/System.Windows.Controls/Panel.cs, src/Runtime/Runtime/System.Windows/Settings.cs
EnableProgressiveRendering in application-wide was not usable in most cases, because can break UI.
But if load progressively by chunks, for example by 10 elements, it's significantly improves UI responsivness
=> Optimize progressive rendering - attach children by chunks

src/Runtime/Controls.Layout.Toolkit/Accordion/ExpandableContentControl.cs, src/Tests/TestApplication/TestApplication/Registry/TestRegistry.cs, src/Tests/TestApplication/TestApplication/TestApplication.OpenSilver.csproj, src/Tests/TestApplication/TestApplication/TestApplication.Silverlight.csproj, src/Tests/TestApplication/TestApplication/Tests/AccordionTest.xaml, src/Tests/TestApplication/TestApplication/Tests/AccordionTest.xaml.cs
DesiredSize is not available.
To test this, go to the TestApplication -> Accordion and expand items.
=> fix: set Accordion ExpandableContentControl size to ActualWidth/Height

src/Runtime/Runtime/System.Windows.Controls.Primitives/Popup.cs
There is a memory leak now.
Steps to reproduce:
1. Create a popup.
2. Open it. The popup is added to the watcher
3. Close the popup. It is not removed from the watcher and the watcher continues to check position in background for closed or removed popup forever.
=> Remember control from position watcher to remove it on closing

src/Runtime/Runtime/System.Windows.Controls/ContentControl.cs, src/Runtime/Runtime/System.Windows.Controls/ContentPresenter.cs, src/Runtime/Runtime/System.Windows.Controls/Control.cs, src/Runtime/Runtime/System.Windows/FrameworkElement.cs
Calling .Count() would enumerate all type's interfaces (reflection) to see if it can find .Count, and then call it (via reflection, again)
=> small speed improvements -- if only first child needed

src/Runtime/Runtime/Core/Rendering/INTERNAL_PopupsManager.cs, src/Runtime/Runtime/System.Windows.Controls.Primitives/Popup.cs, src/Runtime/Runtime/System.Windows.Controls/ComboBox.cs, src/Tests/TestApplication/TestApplication/Registry/TestRegistry.cs, src/Tests/TestApplication/TestApplication/Tests/ComboBoxTest.xaml
Custom style can make DropDownToggleButton not have Content,
but Silverlight still shows the DropDown on ComboBox MouseLeftDown.
To test, go to TestApplication -> ComboBox page and click on the ComboBox labeled to not have a toggle button and still see the dropdown (as the same in Silverlight).
=> feat: show ComboBox drop down when toggle button is not available

src/Runtime/Runtime/System.Windows.Controls/INTERNAL_DateTimePickerBase.cs
DatePicker shows binded value correctly when used stand alone but inside DataForm it enters TextChanged before entering ApplyTemplate.
=> fix: call applytemplate

src/Runtime/Runtime/System.Windows.Controls/Grid.cs, src/Runtime/Runtime/System.Windows/FrameworkElement_HandlingSizeAndAlignment.cs
- when it has static width and height
- when alignment is not stretch in a grid.
=> Fix customlayout

src/Runtime/Runtime/System.Windows.Threading/CoreDispatcher.cs, src/Tests/Runtime.OpenSilver.Tests/Maintenance/MemoryLeak/ItemWithTrackableCallback.cs, src/Tests/Runtime.OpenSilver.Tests/Maintenance/MemoryLeak/MemoryLeakTest.cs
Replace CSHTML5.Interop.ExecuteJavaScriptAsync by Task.Run for the dispatcher.
It fixes memory leak and removes redundancy: it is not necessary to call JavaScript side for async execution.
=> Memory leak in the dispatcher

src/Runtime/Runtime/System.Windows.Controls/ChildWindow.cs
If a client app logic to set the dialog size (e.g. ChildWindow.Width= 0.8 * Window.Width, ChildWindow.Height= 0.8 * Window.Height) when window size changes, it was not working as in UpdateOverlaySize we were resetting the ChildWindow size. This PR fixes that.
=> Fix: Dialog Size Issue

src/Runtime/Runtime/System.Windows.Controls/Control.cs, src/Runtime/Runtime/System.Windows.input/Keyboard.cs
In our project there is a case when FocusManager.SetFocusedElement() throws exception because of null INTERNAL_ParentWindow
=> Prevent null exception on Focus()

src/Runtime/Runtime/System.Windows.Controls/Panel.cs
In our project exception happens when child window with information message appears for a few seconds
=> Prevent progressive loading from throwing IndexOutOfRangeException

src/Runtime/Runtime/System.Windows/UIElement_Events.cs
`enableFocus/disableFocus` is being called many times so it would be better to have asynchronous calls.
=> Use Async call when enabling/disabling focus

src/Compiler/Compiler.TypeScriptDefToCSharp/Model/Function.cs
For example, if we have the following typescript typings:
```
interface UrlStatic {
(): string;
}
```
In this case, the correct typescript output would be:
`Interop.ExecuteJavaScript("$0()", this.UnderlyingJSInstance) `
instead of
`Interop.ExecuteJavaScript("$0.()", this.UnderlyingJSInstance) `
=> Handle the case with empty function name for the typescript generator

src/Runtime/Runtime/Properties/AssemblyInfo.cs
Is it ok to give access to internals for the OpenSilver.ControlsKit.FastControls lib?
=> Make internals visible to OpenSilver.ControlsKit.FastControls

src/Runtime/Runtime/System.Windows.Controls/DragDropTarget_2.cs
If a `ListBoxItem` contains a `TextBox` inside it, it is not focusable because of `onselectstart` (if used with #241). So use `user-select` property instead to prevent text selection on labels but allow textbox focusing
=> Prevent text selection on dragdroptarget

src/Runtime/Runtime/System.Windows.Data/BindingExpression.cs
In some cases DataContext was null, because WeakEventListener was throwing ArgumentNullException
=> Provide correct source for _valueErrorsChangedListener

src/Runtime/Runtime/System.Windows.Controls/TextBoxView.cs
TextBox width was not changing when type or delete text.
```
<Border HorizontalAlignment="Left">
<TextBox Height="20" Text="1234" CustomLayout="True"/>
</Border>
```
=> Fix Textbox sizing under custom layout

src/Runtime/Runtime/System.Windows.Controls/Viewbox.cs
To fix the error "Cannot implicitly convert type 'System.Windows.Data.Binding' to 'System.Windows.UIElement'".
To reproduce, create simple binding: `<Viewbox Child="{Binding Element}"/>`
Originally Viewbox.Child is a dependency property.
=> Viewbox.Child has to be a dependency property

src/Runtime/Runtime/System.Windows.Data/BindingExpression.cs
For example `<TextBox Text="{Binding Test.FirstName, Mode=TwoWay, NotifyOnValidationError=True}"/>`
=> Fix validation for a case when path contains more than one node

src/Runtime/Runtime/System.Windows.Controls/Grid_InternalHelpers.cs
Fix an exception that occurs sometimes on RadGridView scrolling. `Column.Width` or `Row.Height` might be `0*`.
```Method excution failed: System.ArgumentException: 'NaN' parameter cannot be NaN. (Parameter 'value')
at System.Windows.GridLength..ctor(Double value, GridUnitType type)
at System.Windows.Controls.Grid_InternalHelpers.NormalizeWidthAndHeightPercentages_CSSVersion(Grid grid, ColumnDefinitionCollection columnDefinitionsOrNull, RowDefinitionCollection rowDefinitionsOrNull, List`1& normalizedColumnDefinitions, List`1& normalizedRowDefinitions)
at System.Windows.Controls.Grid_InternalHelpers.NormalizeWidthAndHeightPercentages(Grid grid, ColumnDefinitionCollection columnDefinitionsOrNull, RowDefinitionCollection rowDefinitionsOrNull, List`1& normalizedColumnDefinitions, List`1& …
```
=> Fix grid exception when column or row size is 0*

src/Runtime/Runtime/System.Windows.Controls/TextBox.cs, src/Runtime/Runtime/System.Windows.Controls/TextBoxView.cs
TextBox in Silverlight doesn't support spell check.
=> Disable TextBox spellcheck

src/Runtime/Runtime/System.Windows.Printing/PrintDocument.cs
I did some tests with Silverlight implementation.
The BeginPrint event is invoked before any call of PrintPage event.
And PrintedPageCount should be equal to the current number of pages for each PrintPage call.
=> Update PrintedPageCount property and change order of events

src/Runtime/Runtime/System.Windows.input/PointerRoutedEventArgs.cs, src/Runtime/Runtime/System.Windows/UIElement.EventManager.cs, src/Runtime/Scripts/cshtml5.js
* get pageX/pageY from touch event
* ignore mouse events by preventDefault() instead of DispatcherTimer
It fixes exceptions that was appearing in browser console on touch devices.
Also fixed the need to click twice on CheckBox or Button to execute an action on iOS devices.
Published app to test: https://steady-starship-0a0236.netlify.app/
=> Fix touch events

src/Runtime/Runtime/System.Windows.Controls.Primitives/Popup.cs, src/Runtime/Runtime/System.Windows.Controls.Primitives/Selector.cs, src/Runtime/Runtime/System.Windows.Controls/ComboBox.cs
If CustomLayout set to true to a Popup target, the popup shows briefly at 0,0. This [video ](https://drive.google.com/file/d/1IyMHREKJezFq5M4qjUzkotcFtXYbfcMF/view?usp=share_link) shows the issue and [this one](https://drive.google.com/file/d/1PRUo0i1jvRx2Os8k3mHL7WJFGzNhUW_-/view?usp=share_link) the fix. The fix is keeping the popup root hidden until its's position is measured.
=> Fix: Fixed issue Popup showing briefly at 0,0

src/Runtime/Runtime/System.Windows.Markup/StaticResourceExtension.cs
If provide xaml string that contains `StaticResource` to `XamlReader.Load()`, it throws an exception.
```
<Grid xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation'>
<TextBlock Style="{StaticResource FieldNameTextBlock}" Text="Station"/>
</Grid>
```
So, if return `false` from `TryFindTheResource()` the resource will be found in `FindResourceInAppOrSystem()`.
=> Support StaticResource for XamlReader

src/Runtime/Scripts/OpenSilver.js
Controls like DevExpress html editor return objects which we use as-is in our code. and it is returning this to user "null [NOT USABLE DIRECTLY IN C#] (object)"
=> Added support for html objects

src/Runtime/OpenSilver.Xaml/System.Xaml/XamlObjectWriter.cs, src/Runtime/Runtime/System.Windows.Markup/StaticResourceExtension.cs, src/Runtime/Runtime/System.Windows/Application.cs, src/Runtime/Runtime/System.Windows/FrameworkElement.cs
To support XamlReader to get Resources declared in xaml string.
For example
```
<Canvas xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
<Canvas.Resources>
<LinearGradientBrush x:Key="MyBrush">
<GradientStop Offset="0" Color="#ffcccccc"/>
<GradientStop Offset="1" Color="#ffffffcc"/>
</LinearGradientBrush>
</Canvas.Resources>
<Rectangle Width="100"
Height="20"
Fill="{StaticResource MyBrush}"/>
</Canvas>
```
This works if comment out throwing the exception in `ResourceDictionary.EndInit()`. The xml parser for `.Resources` calls `WriteEndObject()`, but not `WriteStartObject()`. Need to be fixed
=> Implement getting Resources from xml parser

src/Runtime/Controls.Data/DataGrid/DataGrid.xaml.cs, src/Runtime/Controls.Data/DataGrid/DataGridRows.cs
The issues is described in this [video](https://drive.google.com/file/d/1WG9SHgNL-SfCv9CvJmnv26c5Uc7o6uec/view?usp=share_link), the progessive loading of rows is stuck if the datagrid was removed and reattached into the visual tree. [This video](https://drive.google.com/file/d/13tyVAqcUlzngf1eFafyU-Z1usECaFVba/view?usp=share_link) has the fix testing.
Here is the sample [XAML File](https://drive.google.com/file/d/18kuJVsUdSQjg8Y602p2iVPOjFLwKs-1Z/view?usp=share_link) and  [CS file](https://drive.google.com/file/d/1KhR_NPrBpRzPtjxA3PxJ-kNARHvFdvh5/view?usp=share_link) to test the issue.
The changes are just about keeping all the variables remembered when detached from visual-tree and resuming the executing with the same variables again once re-attached.
=> Enhancement: Progressive loading of data-grid continues after reattaching to visual tree.

src/Compiler/Compiler/OtherHelpersAndHandlers/FixingServiceReferences.cs, src/Compiler/Compiler/OtherHelpersAndHandlers/Version.cs, src/Targets/OpenSilver.Common.targets
Fixes the issue:
Call a request that contains a parameter with `ref` keyword in `Reference.cs`.
There is an exception in `Prepare()` method of `CSHTML5_ClientBase_1.cs`, that `requestParameters` does not contain a key.
=> Fix generating parameters in Reference.g.cs with ref keyword

src/Runtime/Runtime/System.Windows.Media.Animation/AnimationHelpers.cs, src/Runtime/Runtime/System.Windows.Media.Animation/AnimationTimeline.cs, src/Runtime/Runtime/System.Windows.Media.Animation/ColorAnimation.cs, src/Runtime/Runtime/System.Windows.Media.Animation/ColorAnimationUsingKeyFrames.cs, src/Runtime/Runtime/System.Windows.Media.Animation/DoubleAnimation.cs, src/Runtime/Runtime/System.Windows.Media.Animation/DoubleAnimationUsingKeyFrames.cs, src/Runtime/Scripts/cshtml5.js
If the animation is stopped while it is in progress, the complete callback will never be called so the callback will not be Disposed.
The fix checks if the animation is in progress before calling "stop" and then Disposes the callback.
=> Dispose callback when animation stopped

src/Runtime/Runtime/System.Windows/UIElement.cs
Scenario:
===============
In Timelline Control, when we perform scrolling in Slider control. it adds a child and it recursively invalidates the VirtualizingTimelinePanel. it freezes the UI.
=> fix: Prevent the element in measure queue unecessory.

src/Runtime/Runtime/OpenSilver/Internal/ResizeObserver.cs
Scenario:
=================================
While applying zoom it send value in decimal and it cause the stretching the window.
=> fix: resizeobserver size in decimal.

src/Runtime/Scripts/cshtml5.js
JS event callback had the wrong enum id for when it was keyup
=> fix: fix keyup event not being triggered

src/Compiler/Compiler.Common/Helpers/PathsHelper.cs, src/Compiler/Compiler.ResourcesExtractor/Tasks/ResourcesExtractorAndCopier.cs
It is necessary to run OpenSilver on macOS, for example.
=> Make PathsHelper cross-platform

build/nuspec/OpenSilver.Simulator.nuspec, build/nuspec/OpenSilver.nuspec
We need to add mono.cecil to the Simulator because the resources extractor uses it.
The current version works properly most times because the simulator reuses copier from one of other projects with OpenSilver reference. However, if the simulator will be loaded as a first project, then it can fail.
Also, we do not need mdb and pdb part of mono.cecil, so, it can be removed from OpenSilver to save package size.
=> Include mono.cecil in the Simulator package

src/Runtime/Runtime/Core/Rendering/INTERNAL_Html2dContextReference.cs
Use direct call of `arc` function instead of using `document.invoke2dContextMethod`.
Fixes the incorrect drawing of arcs with clockwise sweep direction.
Example:
```
<Canvas Grid.Row="2" Margin="20">
<Path Width="500" Height="500" Stroke="Black">
<Path.Data>
<PathGeometry>
<PathFigure StartPoint="100 0" IsClosed="False">
<ArcSegment Point="1 0" Size="1 1" SweepDirection="Clockwise" IsLargeArc="False"/>
</PathFigure>
</PathGeometry>
</Path.Data>
</Path>
</Canvas>
```
Expected 
Actual
=> Fix drawing arcs with clockwise sweep direction

src/Targets/OpenSilver.Common.targets
For Blazor projects, the up-to-date checker ignores xaml files out of the box. Add a configuration to check all xaml files too.
=> Configure up-to-date checker to check xaml files

src/Runtime/Runtime/System.Windows/DependencyObject.cs, src/Runtime/Runtime/System.Windows/FrameworkElement_HandlingSizeAndAlignment.cs
1. SizeChanged / LayoutRootSizeChanged - avoid using a list of delegates when we can use a single one
2. remove dependency objects from Brushes's PropertiesWhereUsed
=> memory improvements

src/Compiler/Compiler/OtherHelpersAndHandlers/MonoCecilAssembliesInspector/TypeDefinitionExtensions.cs
Use Equals method, because in some cases MetadataToken can be the same for different types.
One case is RadBusyIndicator and FrameworkElement have the same MetadataToken when CallerArgumentExpressionAttribute is present. As a result this breaks changing VisualStates for controls inside RadBusyIndicator
=> Fix checking subclass in compiler

src/Runtime/Runtime/Core/Rendering/INTERNAL_VisualTreeManager.cs, src/Runtime/Runtime/PublicAPI/CSharpXamlForHtml5_DomManagement.cs, src/Runtime/Runtime/System.Windows.Controls.Primitives/PopupRoot.cs, src/Runtime/Runtime/System.Windows.Controls/ContentPresenter.cs, src/Runtime/Runtime/System.Windows.Controls/Control.cs, src/Runtime/Runtime/System.Windows.Controls/Grid_CSSVersion.cs, src/Runtime/Runtime/System.Windows.Controls/ItemsPresenter.cs, src/Runtime/Runtime/System.Windows.Controls/UserControl.cs, src/Runtime/Runtime/System.Windows.Printing/PrintDocument.PrintOperation.cs, src/Runtime/Runtime/System.Windows.Shapes/Ellipse.cs, src/Runtime/Runtime/System.Windows.Shapes/Line.cs, src/Runtime/Runtime/System.Windows.Shapes/Rectangle.cs, src/Runtime/Runtime/System.Windows.Shapes/Shape.cs, src/Runtime/Runtime/System.Windows.input/KeyboardNavigation.cs, src/Runtime/Runtime/System.Windows.input/PointerRoutedEventArgs.cs, src/Runtime/Runtime/System.Windows/FrameworkElement.cs, src/Runtime/Runtime/System.Windows/FrameworkElement_HandlingSizeAndAlignment.cs, src/Runtime/Runtime/System.Windows/UIElement.cs
This PR fixes 'create element failed' in the browser's console, also it fixes a memory leak related to attaching element back.
I have updated this example: https://github.com/jacob-l/OpenSilverAttachDetach
=> Prevent 'create element failed' error

src/Runtime/Runtime/OpenSilver/DumpHelper.cs, src/Runtime/Runtime/Runtime.OpenSilver.csproj, src/Runtime/Runtime/System.Windows/Application.cs, src/Runtime/Scripts/cshtml5.js
This feature lets quickly debug C# properties right in browser inspector.
To see it in action:
1. Open Elements tab of developers tools (F12)
2. Select an element
3. Open Properties tab
4. Click `dump` property to retrieve all the values
Benefits:
- no need to set breakpoint to see actual value of a property, for example DataContext
- ability to see properties in deployed app
- ability to retrieve specific properties, just call in browser console `document.dumpProperties('id6', 'ActualWidth,ActualHeight')`
=> Getting csharp properties from browser inspector

src/Runtime/Runtime/System.Windows.Controls.Primitives/Selector.Navigation.cs
Steps to reproduce:
1. Set `Host.Settings.ProgressiveRenderingChunkSize = 10;`
2. Add ComboBox `<ComboBox ItemsSource="{Binding Items}" CustomLayout="True" MaxDropDownHeight="500"/>`
3. Add items `for (int i = 0; i < 100; i++) { Items.Add(i.ToString()); }`
4. Run, click on the ComboBox, select an item, and try to open again
```
DEBUG: OnCallBack: OnCallBackFromJavascript: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.ArgumentException: Value does not fall within the expected range.
at System.Windows.UIElement.TransformToVisual(UIElement visual)
at System.Windows.Controls.Primitives.Selector.IsOnCurrentPage(Int32 index, Rect& itemsHostRect, Rect& listBoxItemRect)
at …
```
=> Fix opening ComboBox if progressive loading is enabled

src/Runtime/Runtime/System.Runtime.Serialization/DataContractSerializer.cs, src/Runtime/Runtime/System.ServiceModel/CSHTML5_ClientBase_1.cs
Issue:
================
1. Soap 1.1 supports XML 1.0 Standard. but in current implementation some characters are restricted.
Solution:
================
Replaced XDocument with XmlDocument to parse soap response.
=> Replace Soap Response parsing logic to support xml 1.0 character sets.

src/Tests/TestApplication/TestApplication.OpenSilver.Browser/wwwroot/loading-indicator.js, src/VSExtension/OpenSilverApplicationTemplate/OpenSilverApplication.Browser/wwwroot/loading-indicator.js, src/VSExtension/OpenSilverUwpApplicationTemplate/OpenSilverUwpApplication.Browser/wwwroot/loading-indicator.js
`loadingIndicatorWrapper` is being detached from DOM and it cannot be garbage collected. I think this happens because of the way Blazor replace the contents of the main "App" tag. This PR will check when the reference is not being used anymore, and then it is nullified so this memory can be reclaimed.
=> fix: loadingIndicatorWrapper memory leak

src/Runtime/Runtime/System.Windows.Controls/TextBox.cs
Rolling back my change to TextBox because this broke focusing on it.
This can be tested on TestApplication -> TextBox Properties or TextBox Template.
=> fix: revert capture mouse in TextBox when left button is pressed

src/Compiler/Compiler/2_ConvertingXamlToCSharp/GeneratingCSharpCode.Pass1.cs, src/Compiler/Compiler/2_ConvertingXamlToCSharp/GeneratingCSharpCode.Pass2.cs, src/Compiler/Compiler/2_ConvertingXamlToCSharp/GeneratingCSharpCode.cs, src/Compiler/Compiler/OtherHelpersAndHandlers/Version.cs, src/Runtime/Runtime/OpenSilver/XamlDesignerConstructorStub.cs, src/Runtime/Runtime/Runtime.OpenSilver.csproj, src/Targets/OpenSilver.Common.targets
The idea: for the Xaml Preview feature, we would like to instantiate the App instance, but without creating a Main Window. This allows us to easily reuse global styles.
This PR helps to generate an additional constructor, which will be called by reflection in the Xaml Designer.
=> Generate separate constructor for App class for Xaml Designer usage

src/Runtime/Runtime/System.ServiceModel/CSHTML5_ClientBase_1.cs
Scenario:
===============
In a Web service method, two parameters are used: a String called org and an object called report_date. When we pass a datetime value in report_date during a call, it causes an issue on the server side.
=> fix:handle parameter type difference in soap request.

src/Runtime/Runtime/System.ServiceModel/CSHTML5_ClientBase_1.cs
Issue:
=================
- Method with ref type of parameter cause issue in prepare request.
Resolution:
=================
- The boolean type of variable will be Boolean& so if the variable is the type of ref then use GetElementType() to get the proper type.
=> fix: handled the byref type of parameter in prepare request

src/Targets/OpenSilver.GenerateAssemblyInfo.targets
If internal types are used in the xaml code, then Xaml Designer should get access to it.
=> Add InternalsVisibleTo attribute to expose internal types to XamlDesigner

src/Runtime/Runtime/OpenSilver/Controls/OpenFileDialog.cs
Issue:
============
OpenFileDialog is not working properly in Mozilla Firefox. when we select a file it throws an error.
=> fix: openfiledialog issue for mozilla firefox.

src/Runtime/Runtime/PublicAPI/Interop/HtmlPresenter.cs
I found a regression in OpenSilver 2 related to HtmlPresenter. If the HTML contains style tags, these styles spills out to entire page, affecting the style of other controls. This will use [ShadowDOM](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM) feature to solve this problem.
=> fix: isolate html from htmlpresenter from the remaining of the page

src/Runtime/Runtime/OpenSilver/Internal/Documents/TextContainerTextBlock.cs, src/Runtime/Runtime/System.Windows.Controls/TextBlock.cs, src/Runtime/Runtime/System.Windows.Documents/Run.cs
It fixes the bug: If Run is used as in-line in TextBlock with Binding, The TextBlock.Text is not in sync with Run.Text.
=> fix: TextBlock.Text is not in sync with Run.Text

src/Runtime/Runtime/System.Windows.Controls/DatePicker/DatePicker.cs
// Sample code to produce the issue
stackCalender.Children.Clear(); // clear the parent of datepicker
var datePicker1 = new System.Windows.Controls.DatePicker() {  Width = 100, Height = 30, Visibility = Visibility.Collapsed };            
stackCalender.Children.Add(datePicker1);
datePicker1.Visibility = Visibility.Visible;
datePicker1.IsDropDownOpen = true;
=> Fix: DatePicker were placing incorreclty on early opening

src/Runtime/Blend/Interactivity/InvokeCommandAction.cs
Taken from WPF implementation: https://github.com/microsoft/XamlBehaviorsWpf/blob/main/src/Microsoft.Xaml.Behaviors/InvokeCommandAction.cs
Allows to pass event arguments as a command parameter:
```
<i:Interaction.Triggers>
<i:EventTrigger EventName="EditEnded">
<i:InvokeCommandAction Command="{Binding CustomerFormEditEndedCommand}"
PassEventArgsToCommand="True" EventArgsParameterPath="EditAction"/>
</i:EventTrigger>
</i:Interaction.Triggers>
[RelayCommand]
public void CustomerFormEditEnded(DataFormEditAction e)
{
if (e == DataFormEditAction.Commit)
{
//...
}
}
```
=> Allow to pass event arguments as a command parameter in InvokeCommandAction

src/Runtime/Runtime/System.Windows/DispatcherTimer.cs
This PR addresses an issue where a tick occurs while the UI thread is busy. And the current UI logic stops the timer and runs the timer again.
In this case, the previous tick must be abandoned.
The example is here: https://github.com/jacob-l/OpenSilverTimerSimulator
=> Ensure re-running a stopped dispatcher timer works correctly in the Simulator

src/Runtime/Runtime/System.Windows.Controls/ScrollViewer.cs
Store offset fields, because offsets in ScrollInfo are not updated if quickly move the finger
=> Improve scrolling on touch devices

src/Tests/TestApplication/TestApplication.OpenSilver.Browser/Pages/Index.cs, src/Tests/TestApplication/TestApplication.OpenSilver.Browser/TestApplication.OpenSilver.Browser.csproj, src/Tests/TestApplication/TestApplication.OpenSilver.Browser/wwwroot/index.html, src/Tests/TestApplication/TestApplication.OpenSilver.Simulator/TestApplication.OpenSilver.Simulator.csproj, src/Tests/TestApplication/TestApplication/TestApplication.OpenSilver.csproj
The automated build in GitHub fails during the TestApplication phase due to the 2.2.0 breaking changes warning (example: https://github.com/OpenSilver/OpenSilver/actions/runs/9102305306/job/25021581529).
This PR updates TestApplication to OpenSilver 2.2.0 and make the changes necessary for the 2.2.0 warning to go away.
=> Solve TestApplication 2.2.0 breaking changes warning

src/Tests/Runtime.OpenSilver.Tests/Maintenance/MemoryLeak/MemoryLeakTest.cs, src/Tests/Runtime.OpenSilver.Tests/System.Windows/NameScopeTest.cs
Runtime.OpenSilver.Tests currently does not compile due to TemplateContent having been moved namespaces.
=> Fix Runtime.OpenSilver.Tests

src/Compiler/Compiler/2_ConvertingXamlToCSharp/GeneratingCSharpCode.Pass2.cs, src/Compiler/Compiler/3_ConvertingXamlToFSharp/GeneratingFSCode.Pass2.cs, src/Compiler/Compiler/7_ConvertingXamlToVB/GeneratingVBCode.Pass2.cs, src/Compiler/Compiler/OtherHelpersAndHandlers/AssembliesInspector.cs, src/Compiler/Compiler/OtherHelpersAndHandlers/MonoCecilAssembliesInspector/MonoCecilAssembliesInspectorImpl.cs, src/Tests/TestApplication/TestApplication/Registry/TestRegistry.cs, src/Tests/TestApplication/TestApplication/TestApplication.OpenSilver.csproj, src/Tests/TestApplication/TestApplication/TestApplication.Silverlight.csproj, src/Tests/TestApplication/TestApplication/Tests/ResourceDictionary/CachedResourceDictionary/CachedResourceDictionary.cs, src/Tests/TestApplication/TestApplication/Tests/ResourceDictionary/CachedResourceDictionary/CountableInstance.cs, src/Tests/TestApplication/TestApplication/Tests/ResourceDictionary/CachedResourceDictionary/CountableResourceDictionary.xaml, src/Tests/TestApplication/TestApplication/Tests/ResourceDictionary/CustomPropertyResourceDictionary.cs, src/Tests/TestApplication/TestApplication/Tests/ResourceDictionary/ResourceDictionaryTest.xaml, src/Tests/TestApplication/TestApplication/Tests/ResourceDictionary/ResourceDictionaryTest.xaml.cs, src/Tests/TestApplication/TestApplication/Tests/ResourceDictionary/SomeResourceDictionary.xaml
Even if a dictionary might be referenced in XAML using a subclass
of ResourceDictionary, its definition may be a ResourceDictionary,
causing the Component factory to fail a cast to the subclass. So
we cast to ResourceDictionary to be sure.
=> Allow ResourceDictionary to be inherited and do caching

src/Runtime/Runtime/OpenSilver/Controls/OpenFileDialog.cs
I tested the OpenFileDialog in the simulator for several apps, It works.
=> Remove alert about the simulator from OpenFileDialog

src/Runtime/Scripts/cshtml5.js
- During measure and arrange operation system cannot find element and it create dummy element.
document.getBBox(document.getElementByIdSafe(\"id3968\"));
=> fix: getBBox not found issue.

src/Runtime/Runtime/System.Windows/FrameworkElement.cs
OpenSilver compiler does not allow to set `FrameworkElement.Name` property to special characters like `\` or `"`.
But `XamlReader.Load()` allows it, and then if add the generated element to the page, it tries to set `dataId` attribute and javascript execution fails because the string is not escaped.
=> Fix setting dataId attribute when the Name is set by XamlReader

src/Simulator/Simulator/MainWindow.xaml.cs
Some project runners for VS Code do not use the output folder as their current working directory.
=> Simulator path resolution using Assembly.GetExecutingAssembly().Location

src/Runtime/Runtime/OpenSilver/Controls/SaveFileDialog.cs, src/Tests/TestApplication/TestApplication/Tests/FileDialogTest.xaml, src/Tests/TestApplication/TestApplication/Tests/FileDialogTest.xaml.cs
SaveFileDialog throws when not setting a Filter and calling ShowDialogAsync().
Added tests for scenarios where Filter is set, Filter isn't set, DefaultFilename is set and DefaultExt (extension) is set.
=> fix: enable SaveFileDialog without setting Filter

src/Runtime/Runtime/System.Windows.Controls/ScrollViewer.cs
Cancel scrolling for the case when the mouse is not captured on MouseLeftButtonDown, but becomes captured after a delay. For example, when drag operation started after tap and hold for 200ms.
=> Cancel touch scrolling if the mouse is captured

src/Compiler/Compiler.SharedBuildTasks/Tasks/ResourcesExtractorAndCopier.cs, src/Targets/OpenSilver.MauiHybrid.targets, src/Targets/OpenSilver.Simulator.targets, src/Targets/OpenSilver.WebAssembly.targets
- Added a .lock file mechanism to ensure only one instance of the resource copier runs at a time.
- Implemented file hashing to copy only files that have changed.
=> Implement .lock file synchronization and hash-based copying for resource copier

src/Targets/OpenSilver.MauiHybrid.targets
It looks like the MauiAsset is a proper choice, and it works on Windows and Mac for all targets.
=> Use MauiAsset instead of Content for iPhone builds on Windows

src/Runtime/Blend/Interactions/Interactivity/Layout/MouseDragElementBehavior.cs, src/Runtime/Controls.Toolkit/DragDrop/DragDropTarget.cs, src/Runtime/Controls.Toolkit/DragDrop/ItemDragEventArgs.cs, src/Runtime/Runtime/System.Windows.Controls.Primitives/Thumb.cs, src/Runtime/Runtime/System.Windows.Controls/ComboBoxItem.cs, src/Runtime/Runtime/System.Windows.Controls/InkPresenter.cs, src/Runtime/Runtime/System.Windows.Controls/ScrollViewer.cs, src/Runtime/Runtime/System.Windows/UIElement.cs
Elements like Button, TextBox capture mouse and scrolling does not work on touch screens.
My proposition is to check `AllowScrollOnTouchMove` property instead and set `e.Handled = true` to prevent action like button click after scrolling.
I this case we must set `AllowScrollOnTouchMove = false` for draggable controls. And, if we handle scrolling in the framework, maybe there is no need to set `touchAction` in html.
Related to #970 
https://github.com/user-attachments/assets/61d218cb-4852-46b9-9675-acc881f43a3f
=> Touch scroll over elements that capture mouse
